<template>
    <div>
        <dl>
            <dt>金融</dt>
            <dd>
                <ul>
                    <li>个贷计算器</li>
                    <li>房贷计算器</li>
                    <li>存款计算器</li>
                </ul>
            </dd>
        </dl>
        <dl>
            <dt>生活</dt>
            <dd>
                <ul>
                    <li>秒表</li>
                    <li>电视</li>
                    <li>什么值得买</li>
                </ul>
            </dd>
        </dl>
        <dl>
            <dt>学习</dt>
            <dd>
                <ul>
                    <li>初中教材</li>
                    <li>学习资料</li>
                    <li>编程开发</li>
                </ul>
            </dd>
        </dl>
    </div>
</template>